### ISSUE TITLE
Transliteration of GNU Coreutils

### ISSUE THREAD

**Issue by iamthemuffinman** [EricLagerg/go-coreutils#100]
I would like some clarification on how code should be written for go-coreutils. @EricLagerg Do you still want to do a transliteration of GNU coreutils? I know most of the code I've written hasn't been a transliteration to Go, but more of an implementation of behavior.

Thanks!

**Comment by EricLagerg** [comment]
My original goal was to have a drop-in replacement, including same output in all cases.

Usually this requires a transliteration, but not always. For example, in `wc` I transliterate part of the code (countComplicated, fadvise, etc.) but in other parts I just take the general idea and re-implement it in Go (the actual character counting). Usually this all depends on how the GNU version is written. 

Since Go doesn't have a preprocessor like C does, we can't `#ifdef` stuff. In `wc`, this meant I had to use utf8.RuneCount (or something like that) instead of `#ifdef MB_WCHAR /*handle wide characters */ #else /* handle single-byte characters */`

Keep in mind a lot of the utilities have crufty code from having to handle old machines that Go won't run on, so a transliteration isn't strictly required. If you can rewrite the utility to do the same thing with a comparable speed in idiomatic Go, please do. I fully endorse it.

**Comment by iamthemuffinman** [comment]
Awesome. As I'm writing a utility, I'll look through the GNU version and try to match the output as closely as possible. Haha, my rm is faster than GNU's. ;)

**Comment by EricLagerg** [comment]
Re: `rm` -- go read GNU's `rm`'s source. It's a little bit more in-depth :-)
